# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 322b985f1de6d45247eebcb5bcaca4b0ad01920602dac48dcf1ddba1276bd63cbb8d9a30c9ac4ee48b800486122c0c0f9dd9ba0d56e535560b6fb771b7b4c605

test:
  secret_key_base: 35a39b37f24c499722dfc853d76d501398a2106432f1f444ec8c0388c2f0b0044b180c4ab55fd32e85bbcaffb1de3fc1f5fe2606612355fd46d32aa93df6878b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
